### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by TanTan-TT** [peterKaleta/react-token-autocomplete#3]
Hi
   I use following code 

```
import TokenAutocomplete from 'react-token-autocomplete';
```

But it can not import any object.
I check your package.json, main property is dist/index.js 
and I check that file. It seems not a right file for running.

Could you check it for me? Thanks so much

**Comment by john-osullivan** [comment]
I'm also having trouble getting this thing imported and running, which is a real shame because it's a good looking plug-in.  Just doesn't import (or require) right now.

**Comment by ekosz** [comment]
Just hit this as well.

**Comment by guzmo** [comment]
Same issue

**Comment by eoinmurray** [comment]
same issue

**Comment by peterKaleta** [comment]
fixed, my lacking webpack lingo was at fault
https://github.com/peterKaleta/react-token-autocomplete/pull/4

**Comment by lfrinaldi** [comment]
Hi! I'm having the same issue in 0.5.3 version. Do you guys found a workaround for it?
